= Flask Template
:hp-tags: Python, Flask, Web

For the minimal flask project, the application just returns a string. If we want the page to have a heading and other HTML features, there is an easy option that we build the string  that is wrapper in HTML syntax. But the output is not that good, the code will become so complex that you are not able to change the layout of the web site.

#### Template
Tempalte is used to separate the logic of the application from the layout of the pages. 

To implement templates in Flask, we usually create a folder *templates* inside applicaiton folder, then we can create as many as possible templates inside the directory.

Inside templates, they are mostly standard HTML page, with the only difference that there are some placeholders for the dynamic content enclose in *{{ ... }}* section. We could repalce the placeholders from views by _reder_template_ provided by Flask. For example:

File *_app/templates/index.html_*.
```python
<html>
  <head>
    <title>{{ title }} - blog</title>
  </head>
  <body>
     <h1>Hello, {{ user.name }}!</h1>
  </body>
</html>
```

File *_app/views.py_*.
```python
from flask import render_template
from app import app

@app.route('/')
def index():
	user = {'name':'jing'}
    return render_template('index.html', user=user, title='Home')
```
The _render_template_ takes a template filename and a list of template arguments and returns the rendered template with all the arguments replaced. The _render_template_ invokes the _Jinja2_ which is part of flask framework, Jinja2 substitutes the corresponding values provided as template arguments.


#### Template control
Control statements is given inside *{%...%}*. For example:
```python
{% if title %}
<title>{{ title }} - microblog</title>
{% else %}
<title>Welcome to microblog</title>
{% endif %}
```

#### Template Loop
If the page needs to display a list of elements, it will up to view function how many elements need to be displayed, the template cannot make any assumptions about the number of elements. What the template does is display all the elements that views ask the template to display.
```python
{% for post in posts %}
<div><p>{{ post.author.nickname }} says: <b>{{ post.body }}</b></p></div>
{% endfor %}
```


#### Template inheritance
Tempalte inheritance allows us to move the parts of the apge layout that are common to all templates and put them in a base tempalte from which all other tempaltes are derved. For example:
```
<div>Microblog: <a href="/index">Home</a></div>
<hr>
{% block content %}{% endblock %}
```
In this example, keyword *block* defines the place where the derived templates can insert themselves. Blocks are all gien a unique name, like _content_ in this example, their content can be replaced or enhanced in derived tempaltes.


In the derived template, we use keyword *extend* and *"file name"* to declare parent template, followed by keyword *extend* and blcok name. The content must be enclosed insided the {% block block name%} and {% endblock %}
 