= Reusing Classes
:hp-tags: Java, Thinking in Java

One of the most compelling features about Java is code reuse. But to be revolutionary, you’ve got to be able to do a lot more than copy code and change it.

You reuse code by *creating new classes*, but instead of creating them from scratch, you use _existing classes_ that someone has already built and debugged.

Two ways to accomplish code resuse. 

1. The first is quite straightforward: you simply create objects of your existing class inside the new class. This is called *composition*, because the new class is composed of objects of existing classes. 

* You’re simply reusing the functionality of the code, not its form.

2. It creates a new class as a type of an existing class. You literally take the form of the existing class and add code to it without modifying the existing class. This technique is called *inheritance*.

* Inheritance is one of the cornerstones of object-oriented programming


***
### Inheritance syntax

Inheritance is an integral part of Java (and all OOP languages). It turns out that you’re always doing inheritance when you create a class, because unless you explicitly inherit from some other class, you implicitly inherit from Java’s standard root class *Object*.


