= Deadlock and its prevention
:hp-tags: Deadlock, Operating System

### Deadlock
A deadlock is a situation in which two or more competing actions are each waiting for the other to finish, and thus neither ever does.

A deadlockers situation can arise if *all* of the following conditions hold simultaneously in a system:

1. *Mutual exclusion*: at least one resource must be held in a non-shareable mode. Only one process can use the resource at any given instant of time.
2. *Hold and wait or resource holding*: a process is currently holding at least one resource and requesting additional resources which are being held by other processes.
3. *No preemption*: a resource can be released only voluntarily by the process holding it.
4. *Circular wait*: a process must be waiting for a resource which is being held by another process, which in turn is waiting for the first process to release the resource. In general, there is a set of waiting processes, P = {P1, P2, …, PN}, such that P1 is waiting for a resource held by P2, P2 is waiting for a resource held by P3 and so on until PN is waiting for a resource held by P1.


#### Prevention

* *Lock ordering*

Locks of resources should be obtained in the same order by any thread. A thread cann't get the later lock in the sequence until it has obtained all ealier locks.

The method is efficient, however, it has to know all locks it needs ahead of taking any of the locks.

* *Lock time out*

Put a timeout on lock attempts meaning a thread trying to obtain a lock will only try for so long before giving up. 

If a thread does not succeed in taking all necessary locks within the given timeout, it will backup, free all locks taken, wait for a random amount of time and then retry. 

The random amount of time waited serves to give other threads trying to take the same locks a chance to take all locks, and thus let the application continue running without locking.

A problem with the lock timeout mechanism is that it is not possible to set a timeout for entering a synchronized block in Java.


* *Deadlock detection*

Deadlock detection is a heavier deadlock prevention mechanism aimed at cases in which lock ordering isn't possible, and lock timeout isn't feasible.

Use a directed graph to represent the relationship among locks and threads. 

When a thread requests a lock but the request is denied, the thread can traverse the lock graph to check for deadlocks.

* locks and threads are nodes in the graph.
* if thread owns a lock, there is a edge from lock to thread.
* if thread requests a lock, there is a edge from thread to lock.

After travelling the graph, if there exists a *cycle*, there is a deadlock.


Solution:

1. Release all locks, backup, wait a random amount of time and then retry. 

2. A better option is to determine or assign a priority of the threads so that only one (or a few) thread backs up. The rest of the threads continue taking the locks they need as if no deadlock had occurred. If the priority assigned to the threads is fixed, the same threads will always be given higher priority. To avoid this you may assign the priority randomly whenever a deadlock is detected.

