= A Byte of Python
:hp-tags: Python, basics

##### Numbers
Numbers are maily of two types, _int_ and _float_, there is no long type in Python, the integer can be an integer of any size

##### String
We can specify a string using either _single quotes_ or _double quotes_, single quotes and double quotes are the same in Python, we can specify multiple lines string using _triple quotes_. There is no *char* type in Python. And the string is also immutable in Python as Java.

##### String format
1. use _format()_ method in string
* `'My name is {0}'.format('Jing')`
- number is optional
* `'My name is {name}, {gender}'.format(gender = 'male', name = 'Jing')`
- the arguments should hava the same number, but not have to in the same order.

2. use the format way like _print_ in C
* 'My name is %s %s' % ('Jing', 'Chen')

##### Raw String

If you need to specify some strings where no special processing such as escape sequences are handled, then what you need is to specify a raw string by prefixing *r* or *R* to the string.

Raw way is often used in describing the features of a regular expression.


##### Variables
Naming rules:

1. Thefirstcharacteroftheidentifiermustbealetterofthealphabet(uppercaseASCII or lowercase ASCII or Unicode character) or an underscore ( _ ).
2. Therestoftheidentifiernamecanconsistofletters(uppercaseASCIIorlowercase ASCII or Unicode character), underscores ( _ ) or digits (0-9).
3. Case sensitive

##### local and global variable
* local variable
- When you declare variables inside a function definition, they are not related in any way to other variables with the same names used outside the function, which is a *local* variable.
* global variable
- It is impossible to assign a value to a variable defined outside a function without the *global* statement.
- If you want to assign a value to a name defined at the top level of the program, you have to tell Python that the name is not local, but it is global.
```python
x = 50
def func(): 
  global x
  print 'x is', x

  x= 2
  print 'Changed global x to', x

func()
print 'Value of x is', x
```
The output will be:
```python
x is 50
Changed global x to 2
Value of x is 2
```

##### Default Argument Values
For some functions, you may want to make some parameters *optional* and use *default values* in case the user does not want to provide values for them. This is done with the help of default argument values. You can specify default argument values for parameters by appending to the parameter name in the function definition the assignment operator ( = ) followed by the default value.

* Argument must be assigned a value of it is given a default value in the function definition, which is *required* instead of *optional*.
* Only those parameters which are at the *end of the parameter list* can be given default argument values.

##### Keyword argument
If you have some functions with many parameters and you want to specify only some of them, then you can give values for such parameters by naming them - this is called *keyword arguments*

We use the name (keyword) instead of the position to specify the arguments to the function.

_advantages_:
* we do not need to worry about the *order of the arguments*
* we can give values to only those parameters to which we want to, provided that the other parameters have *default argument values*.

##### variable length parameter
Sometimes you might want to define a function that can take any number of parameters, i.e. variable number of arguments, this can be achieved by using the stars.
```python
def total(initial=5, *numbers, **keywords): 
  count = initial
  for number in numbers: 
    count += number
  for key in keywords: count += keywords[key]
    return count

print total(10, 1, 2, 3, vegetables=50, fruits=100)
```
When we declare a *_starred parameter_* such as *param , then all the positional arguments from that point till the end are collected as a tuple called 'param'.
 
Similarly, when we declare a *double-starred parameter* such as **param, then all the _keyword arguments_ from that point till the end are collected as a dictionary called 'param'.

##### Indentation
Statements which go together must have the same *indentation*. Each such set of statements is called a *block*.

##### docstring
A string on the first logical line of a function is the *docstring* for that function.


The *convention* followed for a docstring is a multi-line string where the first line starts with a capital letter and ends with a dot. Then the second line is blank followed by any detailed explanation starting from the third line.

