= A Byte of Python
:hp-tags: Python, basics

##### Numbers
Numbers are maily of two types, _int_ and _float_, there is no long type in Python, the integer can be an integer of any size

##### String
We can specify a string using either _single quotes_ or _double quotes_, single quotes and double quotes are the same in Python, we can specify multiple lines string using _triple quotes_. There is no *char* type in Python. And the string is also immutable in Python as Java.

##### String format
1. use _format()_ method in string
* `'My name is {0}'.format('Jing')`
- number is optional
* `'My name is {name}, {gender}'.format(gender = 'male', name = 'Jing')`
- the arguments should hava the same number, but not have to in the same order.

2. use the format way like _print_ in C
* 'My name is %s %s' % ('Jing', 'Chen')

##### Raw String

If you need to specify some strings where no special processing such as escape sequences are handled, then what you need is to specify a raw string by prefixing *r* or *R* to the string.

Raw way is often used in describing the features of a regular expression.


##### Variables
Naming rules:

1. Thefirstcharacteroftheidentifiermustbealetterofthealphabet(uppercaseASCII or lowercase ASCII or Unicode character) or an underscore ( _ ).
2. Therestoftheidentifiernamecanconsistofletters(uppercaseASCIIorlowercase ASCII or Unicode character), underscores ( _ ) or digits (0-9).
3. Case sensitive

##### Prompt
* *_raw_input_* () shows a prompt to a person so he knows what to type. 
* Difference between _input_() and _raw_input_()
- The _input_() function will try to convert things you enter as if they were Python code, but it has security problems so you should avoid it.


##### Functions
* Before executes a function, we often to use build in function _isinstance_() to check type.
```python
isinstance(n, int)
# the function returns true if n is an integer
```

##### local and global variable
* local variable
- When you declare variables inside a function definition, they are not related in any way to other variables with the same names used outside the function, which is a *local* variable.
* global variable
- It is impossible to assign a value to a variable defined outside a function without the *global* statement.
- If you want to assign a value to a name defined at the top level of the program, you have to tell Python that the name is not local, but it is global.
```python
x = 50
def func(): 
  global x
  print 'x is', x

  x= 2
  print 'Changed global x to', x

func()
print 'Value of x is', x
```
The output will be:
```python
x is 50
Changed global x to 2
Value of x is 2
```

##### Default Argument Values
For some functions, you may want to make some parameters *optional* and use *default values* in case the user does not want to provide values for them. This is done with the help of default argument values. You can specify default argument values for parameters by appending to the parameter name in the function definition the assignment operator ( = ) followed by the default value.

* Argument must be assigned a value of it is given a default value in the function definition, which is *required* instead of *optional*.
* Only those parameters which are at the *end of the parameter list* can be given default argument values.

##### Keyword argument
If you have some functions with many parameters and you want to specify only some of them, then you can give values for such parameters by naming them - this is called *keyword arguments*

We use the name (keyword) instead of the position to specify the arguments to the function.

_advantages_:
* we do not need to worry about the *order of the arguments*
* we can give values to only those parameters to which we want to, provided that the other parameters have *default argument values*.

##### variable length parameter
Sometimes you might want to define a function that can take any number of parameters, i.e. variable number of arguments, this can be achieved by using the stars.
```python
def total(initial=5, *numbers, **keywords): 
  count = initial
  for number in numbers: 
    count += number
  for key in keywords: count += keywords[key]
    return count

print total(10, 1, 2, 3, vegetables=50, fruits=100)
```
When we declare a *_starred parameter_* such as *param , then all the positional arguments from that point till the end are collected as a tuple called 'param'.
 
Similarly, when we declare a *double-starred parameter* such as **param, then all the _keyword arguments_ from that point till the end are collected as a dictionary called 'param'.

##### Indentation
Statements which go together must have the same *indentation*. Each such set of statements is called a *block*.

##### docstring
A string on the first logical line of a function is the *docstring* for that function.


The *convention* followed for a docstring is a multi-line string where the first line starts with a capital letter and ends with a dot. Then the second line is blank followed by any detailed explanation starting from the third line.

```python
def print_max(x, y):
  '''Prints the maximum of two numbers.

  The two values must be integers.'''
  pass
```


***

### Module
When you import a module, the Python would look for the module you import.
1. if the module is built-in, python knows where to find it.
2. if it was not a compiled module, python searchs the *directories* listed in the *sys.path*, if the module is found, the statements in the body of that module are run. The initialization is done by the first time we import the module.
When you import a modult, PVM would create a *byte-compile* file with extension *.pyc*. It will boost the process of importing a module because a portion of processing required in importing a module is already done.

However, if the module is modified after we imported, the next we imported the module, python creates a new byte-compile file.

We should avoid importing module by star.
In python, remember 

 Explicit is better than Implicit

##### Module's name
Every module has its own name set by python which is assigned to *__name__*, if the __name__ == '__main__', it means that the file is run by user.


##### Package

Packages are just folders of modules with a special init.py file that indicates to Python that this folder is special because it contains Python modules.

***
### Class

* Field

The data part, i.e. _fields_, are nothing but ordinary variables that are bound to the *namespaces* of the classes and objects.

1. instacne variables belongs to each instance of the calss
- are owned by each *individual object/instance* of the class. In this case, each object has its *own copy* of the field
2. class variable belongs to the class
- class variables are shared - they can be accessed by all instances of that class. There is *only one copy* of the class variable and when any one object makes a change to a class variable, that change will be seen by all the other instances.
 


***
* Method
- Class methods have only one specific difference from ordinary functions - they must have an extra first name that has to be added to the beginning of the parameter list, but you do not give a value for this parameter when you call the method, Python will provide it. This particular variable refers to the object itself, and by convention, it is given the name *self* (You can give *any name* for this parameter, it is strongly recommended that you use the name *self*).

 The *self* in Python is equivalent to the *this* pointer in C++ and the *this* reference in Java.
 
***

All class members (including the field members) are *public* and all the methods are *virtual* in Python.


##### Class Definition
1. \___init___(self):
* initializion method, like constructor in Java
* The init method is run as soon as an object of a class is *instantiated*. The method is useful to do any *initialization* you want to do with your object.

2. \___str___(self):
* return the string representation of the object, like toString() method in Java

3. operator overloading:
* \___add(self, other)___:
overload the add operator to change the definition of add operator to apply to object type

Also, \___sub(self, other)___, \___mul(self, other)___, \___rmul(self, other)___, \___cmp___(self, other)

### Inheritance
The derived class could reuse the code of the base class.
Python does not automatically call the constructor of the base class, you have to explicitly call it yourself.

 Python allows multiple inheritance.

Inside your class constructor:
```python
super(derive_class, self).__init__()
```
or
```python
derive_class.__init__()
```



#### Polymorphism

A function can take arguments with different types is called *polymorphic*. Polymorphism also means that derived classes could be used by anywhere base class is used.

If all of the operations inside the function can be applied to the type, the function can be applied to the type.

#### Method Binding
Python always starts looking for methods in the *actual type*, if it couldn't  find the method, it starts looking for the methods in its base classes one by one in the order they are specified in the tuple of the class definition.


***

## Libraries

### pickle

Python provides a standard module called *pickle* using which you can store any plain Python object in a file and then get it back later. This is called storing the object *persistently*.

1. pickle.dump(file, python_object)
* The statement would store python_object into file.
2. pickle.loads