= Python re module
:hp-tags: Python, regex

Regular expressions are a powerful language for matching text patterns. This page gives a basic introduction to regular expressions themselves sufficient for our Python exercises and shows how regular expressions work in Python. The Python "_re_" module provides regular expression support.

***
#### Basic pattern
* ordinary characters just match themselves exactly, including numbers and characters
* a period matches any single character except newline '\n'
* \t, \n, \r -- tab, newline, return
* ^ = start, $ = end -- match the start or end of the string
* \b matches the start or the end of the word
* \w matches a letter or a digit or a underscore
* \s matches a single whitespace
* \d matches a digit
* repetition
- + 1 or more occurrences of the pattern to its left
- * 0 or more occurrences of the pattern to its left
- ? match 0 or 1 occurrences of the pattern to its left
- {n} matches exactly n occurrences of the pattern to its left
- {n,} matches at least n occurences of the pattern to its left
- {n, m} matches n to m occurences of the pattern to its left
- *lazy*, if above patterns are followed by ?, it means the pattern matches the string as small as possible.
* *Square bracket*
- square brackets can be used to indicate a set of chars
- a period just means a literal dot
- You can also use a dash to indicate a range, so [a-z] matches all lowercase letters. 

In Python, the '*r*' at the start of the pattern string designates a python "raw" string which passes through backslashes without change which is very handy for regular expressions (Java needs this feature badly!).

***
#### Basic rule
* The search proceeds through the string from start to end, stopping at the *first match* found
* All of the pattern must be matched, but not all of the string
* *Leftmost & Largest*
- First the search finds the leftmost match for the pattern, and second it tries to use up as much of the string as possible

***
#### _re.search_ (pattern, str)
The __re.search()__ method takes a regular expression pattern and a string and searches for that pattern within the string. If the search is successful, _search()_ returns a match object or *None* otherwise.
```python
str = 'an example word:cat!!'
match = re.search(r'word:\w\w\w', str)
# If-statement after search() tests if it succeeded
  if match:                      
    print 'found', match.group() ## 'found word:cat'
  else:
    print 'did not find'
```

