= SQL review
:hp-tags: Database, SQL

SQL is a standard language for accessing and manipulating databases.

SQL stands for **S**tructured **Q**uery **L**anguage

A database most often contains one or more **table**s. Each table is identified by a name (e.g. "Customers" or "Orders"). Tables contain *records* (rows) with data.


* SQL is NOT case sensitive: select is the same as SELECT

##### SELECT
The *SELECT* statement is used to select data from a database.
```SQL
SELECT * FROM table_name;
```

##### SELECT DISTINCT
The *SELECT DISTINCT* statement is used to return only distinct (different) values.
```SQL
SELECT DISTINCT column_name,column_name
FROM table_name;
```

##### LIMIT
The *LIMIT* clause is used to specify the number of records to return.

The clause can be very useful on large tables with thousands of records. Returning a large number of records can impact on performance.
```sql
SELECT column_name(s)
FROM table_name
LIMIT number;
```

##### WHERE
The *WHERE* clause is used to filter records.
```SQL
SELECT column_name,column_name
FROM table_name
WHERE column_name operator value;
```
SQL requires single quotes around _text_ values (most database systems will also allow double quotes).

However, _numeric_ fields should not be enclosed in quotes:

##### AS
SQL aliases are used to temporarily rename a _table_ or a _column heading_.

* For column
```sql
SELECT column_name AS alias_name
FROM table_name;
```

* For tables
```sql
SELECT column_name(s)
FROM table_name AS alias_name;
```

Aliases can be useful when:

* There are more than one table involved in a query
* Functions are used in the query
* Column names are big or not very readable
* Two or more columns are combined together

For example
```sql
SELECT CustomerName, CONCAT(Address,', ',City,', ',PostalCode,', ',Country) AS Address
FROM Customers;
```


##### AND & OR
The *AND* operator displays a record if both the first condition AND the second condition are true.

The *OR* operator displays a record if either the first condition OR the second condition is true.


##### ORDER BY
The *ORDER BY* keyword is used to sort the result-set by one or more columns.

The *ORDER BY* keyword sorts the records in *_ASC_* order by default. To sort the records in a descending order, you can use the *_DESC_* keyword.

```SQL
SELECT column_name, column_name
FROM table_name
ORDER BY column_name ASC|DESC, column_name ASC|DESC;
```

##### INSERT INTO ... VALUES
The *INSERT INTO* statement is used to insert new records in a table.

It is possible to write the INSERT INTO statement in two forms.

* The first form does not specify the column names where the data will be inserted, only their values:

```SQL
INSERT INTO table_name
VALUES (value1,value2,value3,...);
```

* The second form specifies both the column names and the values to be inserted:
```SQL
INSERT INTO table_name (column1,column2,column3,...)
VALUES (value1,value2,value3,...);
```

In the second method, the unspecified column would be filled with *null*.


##### UPDATE ... SET
The *UPDATE* statement is used to update existing records in a table.
```SQL
UPDATE table_name
SET column1=value1,column2=value2,...
WHERE some_column=some_value;
```

The *WHERE* clause specifies which record or records that should be updated. If you omit the WHERE clause, all records will be updated!


##### DELETE FROM
The *DELETE* statement is used to delete records in a table.
```SQL
DELETE FROM table_name
WHERE some_column=some_value;
```

##### IN
The *IN* operator allows you to specify multiple values in a WHERE clause. 
```sql
SELECT column_name(s)
FROM table_name
WHERE column_name IN (value1,value2,...);
```

##### BETWEEN
The *BETWEEN* operator is used to select values within a range.

To exclude a range, use *NOT BETWEEN*

The values can be numbers, text, or dates.
```SQL
SELECT column_name(s)
FROM table_name
WHERE column_name BETWEEN value1 AND value2;
```

##### UNION
The SQL *UNION* operator combines the result of two or more *SELECT* statements.

Notice that each SELECT statement within the UNION must have the same number of columns. The columns must also have similar data types. Also, the columns in each SELECT statement must be in the same order.
```sql
SELECT column_name(s) FROM table1
UNION
SELECT column_name(s) FROM table2;
```
UNION would remove duplicates by default. To allow duplicate, use *UNION ALL*

```SQL
SELECT column_name(s) FROM table1
UNION ALL
SELECT column_name(s) FROM table2;
```

##### SELECT ... INTO
The SELECT INTO statement copies data from one table and inserts it into a new table.

The SELECT INTO statement selects data from one table and inserts it into a new table.

```sql
SELECT *
INTO newtable [IN externaldb]
FROM table1;
[WHERE]
```

##### CREATE DATABASE
```SQL
CREATE DATABASE dbname;
```

##### CREATE TABLE
The CREATE TABLE statement is used to create a table in a database.

Tables are organized into rows and columns; and each table must have a name.
```SQL
CREATE TABLE table_name
(
column_name1 data_type(size),
column_name2 data_type(size),
column_name3 data_type(size),
....
);
```
The column_name parameters specify the names of the columns of the table.

The data_type parameter specifies what type of data the column can hold (e.g. varchar, integer, decimal, date, etc.).

The size parameter specifies the maximum length of the column of the table.

##### SQL views
In SQL, a view is a virtual table based on the result-set of an SQL statement.

A view contains rows and columns, just like a real table. The fields in a view are fields from one or more real tables in the database.

You can add SQL functions, WHERE, and JOIN statements to a view and present the data as if the data were coming from one single table.

```sql
CREATE VIEW view_name AS
SELECT column_name(s)
FROM table_name
WHERE condition
```
A view always shows *up-to-date* data! The database engine recreates the data, using the view's SQL statement, every time a user queries a view.

##### SQL Joins

* *INNER JOIN*: Returns all rows when there is at least one match in BOTH tables
- The *INNER JOIN* keyword selects all rows from both tables as long as there is a match between the columns in both tables.
```sql
SELECT column_name(s)
FROM table1
INNER JOIN table2
ON table1.column_name=table2.column_name;
```

* *LEFT JOIN*: Return all rows from the left table, and the matched rows from the right table
- The LEFT JOIN keyword returns all rows from the left table (table1), with the matching rows in the right table (table2). 
- The result is *NULL* in the right side when there is no match.

```SQL
SELECT column_name(s)
FROM table1
LEFT JOIN table2
ON table1.column_name=table2.column_name;
```

* *RIGHT JOIN*: Return all rows from the right table, and the matched rows from the left table
- The RIGHT JOIN keyword returns all rows from the right table (table2), with the matching rows in the left table (table1).
- The result is *NULL* in the left side when there is no match.
```sql
SELECT column_name(s)
FROM table1
RIGHT JOIN table2
ON table1.column_name=table2.column_name;
```
* *FULL JOIN*(disabled in MySQL): Return all rows when there is a match in ONE of the tables
- The FULL OUTER JOIN keyword returns all rows from the left table (table1) and from the right table (table2).
- if there are rows that do not have matches in the other table, those rows will be listed as well.
```sql
SELECT Customers.CustomerName, Orders.OrderID
FROM Customers
FULL OUTER JOIN Orders
ON Customers.CustomerID=Orders.CustomerID
ORDER BY Customers.CustomerName;
```

##### SQL injection
SQL injection is a technique where malicious users can inject SQL commands into an SQL statement, via *web page input*.

Injected SQL commands can alter SQL statement and compromise the security of a web application.

The only proven way to protect a web site from SQL injection attacks, is to use *SQL parameters* also known as *prepared statment*.
```java
java.sql.PreparedStatement stmt = 
connection.prepareStatement(
"SELECT * FROM table WHERE EMAIL = ?");

/* The statement below sets "?" to an actual value that
is stored in the email variable, we are also assuming
that the email variable is set beforehand: */

stmt.setString(1, email);

stmt.executeQuery();
```
The key feature of a prepared statement is the fact that values can be plugged into the query after the query is “*prepared*”, and ready to be executed.

SQL parameters are values that are added to an SQL query at execution time, in a controlled manner.

*Advantage of prepared statements*

* Better performance

The DBMS will parse, compile, and perform query optimization on the *template*.

Because of the fact that a prepared statement does not have to be compiled and optimized each and every time the values in the query change, it offers a distinct performance advantage.

* Prevent SQL injection

There is absolutely no way that the data input by a hacker can be interpreted as SQL, and there’s no way that the hacker could run his own SQL on your application. 

Any input that comes in is only interpreted as *data*, and can not be interpreted as part of your own application’s SQL code



