= Maven in 5 Minutes
:hp-tags: Maven, Java

#### Installation
Install by *homebrew* on Mac OS or *apt-get* on Ubuntu

Make sure I install maven correctly by:
```
mvn --version
```

#### Creating a Project
You will need somewhere for your project to reside, create a directory somewhere and start a shell in that directory. On your command line, execute the following Maven goal:

```
mvn archetype:generate -DgroupId=io.github.milantracy -DartifactId=my_app -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
```

mvn would generate a folder named _my_app_, inside the directory, the structure would be maven [standard project structure] (https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html)

```
my-app
|-- pom.xml
`-- src
    |-- main
    |   `-- java
    |       `-- io
    |           `-- github
    |               `-- milantracy
    |                   `-- App.java
    `-- test
        `-- java
            `-- io
                `-- github
                    `-- milantracy
                        `-- AppTest.java
```
The *src/main/java* directory contains the project source code, the *src/test/java* directory contains the test source, and the *pom.xml* file is the project's *Project Object Model*, or POM.


#### The POM
The pom.xml file is the core of a project's configuration in Maven. It is a single configuration file that contains the majority of information required to build a project in just the way you want. 

#### Build the Project
```
mvn package
```

Unlike the first command executed (archetype:generate) you may notice the second is simply a single word - *package*. Rather than a goal, this is a _phase_. A phase is a step in the build lifecycle, which is an ordered sequence of phases. When a phase is given, Maven will execute every phase in the sequence up to and including the one defined. For example, if we execute the compile phase, the phases that actually get executed are:

1. validate
2. generate-sources
3. process-sources
4. generate-resources
5. process-resources
6. compile

mvn would generate a directory named target in the project directory, run the code by
```
java -cp target/my_app-1.0-SNAPSHOT.jar io.github.milantracy.App
```

#### Maven Phases
These are the most common _default lifecycle phases_ executed.

1. *validate*: validate the project is correct and all necessary information is available
2. *compile*: compile the source code of the project
3. *test*: test the compiled source code using a suitable unit testing framework. These tests should not require the code be packaged or deployed
4. *package*: take the compiled code and package it in its distributable format, such as a _JAR_.
5. *integration-test*: process and deploy the package if necessary into an environment where integration tests can be run
6. *verify*: run any checks to verify the package is valid and meets quality criteria
7. *install*: install the package into the local repository, for use as a dependency in other projects locally
8. *deploy*: done in an integration or release environment, copies the final package to the remote repository for sharing with other developers and projects.