= Python re module
:hp-tags: Python, regex

Regular expressions are a powerful language for matching text patterns. This page gives a basic introduction to regular expressions themselves sufficient for our Python exercises and shows how regular expressions work in Python. The Python "_re_" module provides regular expression support.

***
#### Basic pattern
* ordinary characters just match themselves exactly, including numbers and characters
* a period matches any single character except newline '\n'
* \t, \n, \r -- tab, newline, return
* ^ = start, $ = end -- match the start or end of the string
* \b matches the start or the end of the word
* \B matches the non-start nor non-end of the word
* \w matches a letter or a digit or a underscore
* \W matches non-letter nor non-digit nor underscore
* \s matches a single whitespace
* \S matches a non-whitespace
* \d matches a digit
* \D matches a non-digit
* repetition
- + 1 or more occurrences of the pattern to its left
- * 0 or more occurrences of the pattern to its left
- ? match 0 or 1 occurrences of the pattern to its left
- {n} matches exactly n occurrences of the pattern to its left
- {n,} matches at least n occurences of the pattern to its left
- {n, m} matches n to m occurences of the pattern to its left
- *lazy*, if above patterns are followed by ?, it means the pattern matches the string as small as possible.
* *Square bracket*
- square brackets can be used to indicate a set of chars
- a period just means a literal dot
- you can also use a dash to indicate a range, so [a-z] matches all lowercase letters.
* Branch
- a|b matches pattern a or pattern b
* *Group*
- the "group" feature of a regular expression allows you to pick out parts of the matching text.
- to do this, add parenthesis ( ) around the patterns which are supposed to be in a gtoup
- in this case, the parenthesis do not change what the pattern will match, instead they establish logical "groups" inside of the match text.
- result of group extraction is *1-based*, however, group 0 will be the whole match

In Python, the '*r*' at the start of the pattern string designates a python "raw" string which passes through backslashes without change which is very handy for regular expressions (Java needs this feature badly!).
 
***
#### Basic rule
* The search proceeds through the string from start to end, stopping at the *first match* found
* All of the pattern must be matched, but not all of the string
* *Leftmost & Largest*
- First the search finds the leftmost match for the pattern, and second it tries to use up as much of the string as possible

***
#### _re.search_ (pattern, str)
The __re.search()__ method takes a regular expression pattern and a string and searches for that pattern within the string. If the search is successful, _search()_ returns a match object or *None* otherwise.
```python
import re
str = 'an example word:cat'
match = re.search(r'word:\w\w\w', str)
  if match:                      
    print 'found', match.group() 
  else:
    print 'did not find'
```
Output:
```
found word:cat
```

***
#### _re.match_ (pattern, str, [start position])
The _re.match_() method is similar to _re.search()_, however, _re.match()_ checks for a match only at the beginning of the string, while _re.search()_ checks for a match anywhere in the string.
```python
import re

result1 = re.match("c","abcde");
if(result1):
    print("result1: "+result1.group());
else:
    print("nothing");

result2 = re.search("c","abcde");
if(result2):
    print("result2: "+result2.group());
```
Output:
```
nothing
result2: c
```

***
#### _re.split_ (pattern, string, maxsplit=0)
Split string by the occurrences of pattern. maxsplit defines the maximum fragment of result. By default, there is no limit.
```python
import re
re.split('\s+', 'chen jing    cj')
```
Output:
```
['chen', 'jing', 'cj']
```
***

#### _re.findall_ (pattern, string, flags=0)
_findall_() finds *all* the matches and returns them as *a list of strings*, with each string representing one match.


