= Hash in Java
:hp-tags: Java, Hashmap, Hash
   


### hashCode and equals()
By default, the _hashCode()_ function returns a *integer* wihch is converted from the internal address of the object.
This is typically implemented by converting the internal address of the object into an integer

_equals_ () method only returns true when two objects are the same object in the memeoty regardless of their content.


You must override hashCode() in every class that overrides equals(). Failure to do so will result in a violation of the general contract for Object.hashCode(), which will prevent your class from functioning properly in conjunction with all hash-based collections, including HashMap, HashSet, and Hashtable.


### HashMap implemtation
HashMap maintains an array of *buckets*. Each bucket is a linkedlist of key/value pairs encapsulated as *Entry* objects

This array of buckets is called table. Each node of the linked list is an instance of a private class called *Entry*

```java
transient Entry[] table;
```
An entry is a private static class inside HashMap which implements Map.Entry
```java
private static class Entry<K,V> implements Map.Entry<K,V> {
     final K key;
     final int hash;
     V value;
     Entry<K,V> next;
}
```

