= Flask learning
:hp-tags: Python, Flask, Web

The article introduces the basics and my learning process of flask framework.

***
#### Preparation
* install _pip_
- reference: https://pip.pypa.io/en/stable/installing/
* isntall _virtualenv_
- The more projects you have, the more likely it is that you will be working with different versions of Python itself, or at least different versions of Python libraries. Virtualenv does provide a clever way to keep different project environments *isolated*.
- `sudo pip install virtualenv`
- reference: https://virtualenv.pypa.io/en/latest/installation.html
* configure virtual environment
- `mkdir myproject`
- `cd myproject`
- `virtualenv venv`
* activate virtual environment
- . venv/bin/activate
* install dependent libraries
- `pip install falsk`

***
#### Minimal Flask Application
```python
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello World!'

if __name__ == '__main__':
    app.run()
```
In above code:

1. First we imported the *Flask* class. An instance of this class will be our *WSGI* (**W**eb **S**erver **G**ateway **I**nterface) application.
2. Next we create an instance of this class. The first argument is the name of the application’s module or package. If you are using a single module (as in this example), you should use __name__ because depending on if it’s started as application or imported as module the name will be different ('__main__' versus the actual import name). This is needed so that Flask knows where to look for templates, static files, and so on.
3. We then use the *_route_*() decorator to tell Flask what *URL* should trigger our function.
4. The function is given a name which is also used to generate URLs for that particular function, and returns the message we want to display in the user’s browser.
5. Finally we use the *_run_*() function to run the local server with our application. The if __name__ == '__main__': makes sure the server only runs if the script is executed directly from the Python interpreter and not used as an imported module.

***
#### Externally visible Server:

If you have *debug disabled* or *trust the users* on your network, you can make the server publicly available simply by changing the call of the _run_() method to look like this:
```python
app.run(host='0.0.0.0')
```

***
#### Debug Mode
The _run_() method is nice to start a local development server, but you would have to restart it manually after each change to your code.
If you enable debug support the server will reload itself on code changes, and it will also provide you with a helpful debugger if things go wrong. Enable debug by:
```python
app.run(debug=True)
```

***
#### Route
The *_route_*() decorator is used to bind a function to a URL. 

```python
@app.route('/')
def index():
    return 'Index Page'

@app.route('/hello')
def hello():
    return 'Hello World'
```

##### Variable Rules
To add variable parts to a URL you can mark these special sections as *<variable_name>*. 
Such a part is then passed as a keyword argument to your function. Optionally a converter can be used by specifying a rule with *<__converter__:variable_name>*

```python
@app.route('/user/<username>')
def show_user_profile(username):
    # show the user profile for that user
    return 'User %s' % username

@app.route('/post/<int:post_id>')
def show_post(post_id):
    # show the post with the given id, the id is an integer
    return 'Post %d' % post_id
```
The following converters exist:

1. *_int_* accepts integers
2. *_float_* accepts floating point value
3. *_path_* accept values like the default but also accepts slashes

##### Unique URLs / Redirection Behavior
Flask’s URL rules are based on *Werkzeug’s* routing module. The idea behind that module is to ensure beautiful and unique URLs based on precedents laid down by Apache and earlier HTTP servers.

Look at following code:
```python
@app.route('/projects/')
def projects():
    return 'The project page'

@app.route('/about')
def about():
    return 'The about page'
```
1. In the first case, the canonical URL for the projects endpoint has a *trailing slash*. In that sense, it is similar to a folder on a file system. Accessing it without a trailing slash will cause Flask to *redirect* to the canonical URL with the trailing slash.

2. In the second case, however, the URL is defined without a trailing slash, rather like the pathname of a file on UNIX-like systems. Accessing the URL with a trailing slash will produce a *404 “Not Found”* error.

##### URL Building

***

#### HTTP Methods
By default, a route only answers to *_GET_* requests, but that can be changed by providing the methods argument to the route() decorator. 
```python
@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        do_the_login()
    else:
        show_the_login_form()
```

