= Python Static, Instance variable
:hp-tags: Python

#### Static variable and Instance variable
Generally speaking, *instance variables* are unique to each instance and *class variables* are attributes and methods shared by instances of the class.
```
class Dog(object):
	
    kind = 'canine'		# class variable
    
    def __init__(self, name):
    	self.name = name		# instance variable

a = Dog('Ben')
b = Dod('Cam')
```

In the above code, vairiable _kind_ is class variable, it is shared by all instances of Dog class. a and b both have kind which is canine. Variable _name_ is instance variable, each instance of Dog keeps its own instance variable, unique to each other, for example, a's name is Ben and b's name is Cam.


Shared data like class variable can have possibly surprising effects with involving mutable objects such as lists and dictionaries.


#### Value change of class variable and instance variable
Python dosen't really have static variable in the sense that C++ and Java do. We have to notice the difference on value change when we modify the static value by instance or by class. For example:
```python
class Test():
	i = 2
t = Test()
print t.i	# 2
t.i = 5
print t.i	# 5
print Test.i	# 2

Test.i = 6
print t.i	# 5
print Test.i	#6
```

In the above example, if we modify the static variable by instance, the instance variable got out of the satatic variable, since it re-bound with the instance namespace, which is distinct from Test namespace.

If you want to change the value of a static variable, you must change it within the scope where it was originally defined.

For the same reason, when we modify the value of the class variable via the class name, it doesn't affect the value of instance variable even though they share the same variable name.


#### Python lookup order

When we use a variable via instance, like self.xxx, search order is:

1. instance
2. class
3. base class

It also works for method lookup.