= Hash in Java
:hp-tags: Java, Hashmap, Hash
   


### hashCode and equals()
By default, the _hashCode()_ function returns a *integer* wihch is converted from the internal address of the object.
This is typically implemented by converting the internal address of the object into an integer

_equals_ () method only returns true when two objects are the same object in the memeoty regardless of their content.


You must override hashCode() in every class that overrides equals(). Failure to do so will result in a violation of the general contract for Object.hashCode(), which will prevent your class from functioning properly in conjunction with all hash-based collections, including HashMap, HashSet, and Hashtable.


### HashMap implemtation
HashMap maintains an array of *buckets*. Each bucket is a linkedlist of key/value pairs encapsulated as *Entry* objects

This array of buckets is called table. Each node of the linked list is an instance of a private class called *Entry*

```java
transient Entry[] table;
```
An entry is a private static class inside HashMap which implements Map.Entry
```java
private static class Entry<K,V> implements Map.Entry<K,V> {
     final K key;
     final int hash;
     V value;
     Entry<K,V> next;
}
```
Each entry object exists only for a particular key but values may change (if same key is reinserted later with a different value) - hence key is final while value is not
 
Each Entry object has a field called next which points to the next Entry thus behaving like a singly linked list.
 
The hash field stores the hashed value of the key
 

* *constructor:*

HashMap provides overloaded constructors with parameters for initial capacity and load factor but typically no args constructor is the one most frequently used
 
default values of these fields are :

*initial capacity* : 1 << 4 (ie 16)

*load factor* : 0.75

* *capacity:*
 
Whenever the element count of the hashmap reaches the load factor fraction of capacity, the map is resized and capacity is *doubled*

If capacity provided by client is a power of 2, then real capacity will be same as capacity, else real capacity = nearest power of 2 > provided capacity

maximum capacity is 1<<30 (ie 2 ^30) if capacity provided is greater than that, then real capacity = 2^30

 capacity indicates the size of the table array (the array of buckets) and not the number of key-value pairs the HashMap can support.
 
 
* *Fail Fast:*

Fail-fast iterator :
 
HashMap specifications need that iterators should throw _ConcurrentMoodificationException_ if the map contents are changed while a client is iterating over an iterator

This done by keeping track of number of modifications. HashMap has a member int variable named *_modCount_* which is incremented everytime the map is altered (any invocation of put(), remove(), putAll() or clear() methods).

There would be a variable in iterator whihc stores the number of modification when the iterator is created. It is initialized to be the same as *_modCount_*, every time _next_ (), _hasNext_(), 
