= JavaScript Beginner
:hp-tags: JavaScript

### Values, Types, and Operators
There are *basic* types of values in JavaScript: *numbers*, *strings*, *Booleans*, *objects*, *functions* and *undefined value*.

* *Numbers*

JavaScript uses a fixed number of bits, namely *64* of them  to store a single number value.

Those bits also store negative numbers, so one bit indicates the sign of the number. To represent nowhole numbers, float or double, some of the bits are used to store the *position of the decimal point*. The actual integer number that can be stored is more in the range of 9 quadrillion.

For very bit or very small numbers, you ca also use scientific notation by adding an "e" for exponent, followed by the exponent of the number.

Calculations with integers that doen't overflow are guaranteed to always be precise, unfortunately, calculation with fractional numbers are general not, many numbers lose some precision when only 64 bits are available to store them. The important thing is to be aware of it and treat fraction digital numbers as *approximateions* rather than precision values.


There are three *special values* that are considered numbers don't behave like normal numbers.

The first two are _Infinity_ and _-Infinity_, _Infinity - 1_ is still infinity. _NaN_ stands for "Not a Number", 

