= Java 8 in action
:hp-tags: Java, Java8


With the Java 8 relaese, Java provided support for functional programming, new Javascript engine, new APTs for data time manipulation, new streaming API.

There are lots of features added to Java 8, the most significant ones are mentioned below:

* *Lambda expression* adds functional processing capability to Java

* *Method references* references functions by their names instead of invoking them directly, we can also use function as parameter.

* *Default method* enables interface to provide non-abstract method, which includes default implementation.

* *New tools* like new compiler tools and utilities are added.

* *Stream API* facilitates pipeline processing

* *Nashorn*, a new Java based engine to execute JavaScript code

#### Lambda Expression
Lambda expressions are introduced in Java 8 and are touted to be the biggest feature of Java 8. It facilitates *functional programming*, and simplfies the development a lot.

* Syntax

A lambda expression is characterized by the syntax:

 (parameter) -> {expression body}

* Characteristics

- *Optional type declaration*. No need to declare the type of a parameter. The compiler can inference the same from the value of the parameter

- *Optional parenthesis around parameter*. No need to declare a sngle parameter in parenthesis. For multiple parameters, parentheses are required.

- *Optional curly braces*. No need to use curly braces in expression body if the body contains a single statement.

- *Optional return keyword*. The compiler automatically returns the vale if the body has a single expression to return the value. Curly braces are required to indicate that expression returns a value.


Lambda expressions are used prmarily to define *inline implementation* of a functional interface, such as an interface with a single method only.

Lambda expression eliminates the need of_anonymous class_ and gives a very simple yet powerful functional programming capacity to Java.

```java
public class Test{
	public static void main(String[] args){
    	Messager messager = message -> System.out.println("Received: " + message);
    }
    
    Interface Messager{
    	void showMessage(String message);
    }
}
```




#### Method References

Method references help to point to methods by their names. A method reference is described using *double colon symble* (::).

A method reference can be used to point the following types of methods

- Static methods
- Instance methods
- Constructor using new operator operator

For example, we can passed _System.out::println_ as a static method reference.


#### Functional Interfaces
*Functional interfaces* have a single functionality to exhibit. For example, interface _Comparable_ provides only one single method _compareTo_ which is used for comparison.

Java 8 provides a lot of functional interfaces to be used extensively in lambda expression.

_java.util.Function_ defines a list of functional interfaces.


*IMPORTANT*

A functional interface is an interface that has only one abstract method, and represents a single function contract.

Lambda expressions require these functional interfaces are restricted to single method, *anonymous interfaces* still need to be used for implementing multiple method interfaces.


#### Default Methods in interfaces
Java 8 introduces a new concept of default method implementation in interfaces. This capability is added for backward compatibility so that old interfaces can be used to leverage the lambda expression.

For example, there is no _forEach_ method declaration in _List_ before Java 8, adding the method woud break the legacy code implementation. Default method could provide the implementation for the method, in this way, the class implementation does not have to implement the method.

* Syntax
Using keyword *default* before method signature
```java
public interface xxx{
	default void defaultMethod(){
    	/* implement here */
    }
}
```