= JavaScript Beginner
:hp-tags: JavaScript

### Values, Types, and Operators
There are *basic* types of values in JavaScript: *numbers*, *strings*, *Booleans*, *objects*, *functions* and *undefined value*.

* *Numbers*

JavaScript uses a fixed number of bits, namely *64* of them  to store a single number value.

Those bits also store negative numbers, so one bit indicates the sign of the number. To represent nowhole numbers, float or double, some of the bits are used to store the *position of the decimal point*. The actual integer number that can be stored is more in the range of 9 quadrillion.

For very bit or very small numbers, you ca also use scientific notation by adding an "e" for exponent, followed by the exponent of the number.

Calculations with integers that doen't overflow are guaranteed to always be precise, unfortunately, calculation with fractional numbers are general not, many numbers lose some precision when only 64 bits are available to store them. The important thing is to be aware of it and treat fraction digital numbers as *approximateions* rather than precision values.


There are three *special values* that are considered *numbers* don't behave like normal numbers.

The first two are *_Infinity_* and *_-Infinity_*, _Infinity - 1_ is still infinity. *_NaN_* stands for "Not a Number", even though it is a value of the number type. The result will be _NaN_ for any *numeric operations* that don't yield a precise, meaningful value.

Further arithmetic operations on NaN keep producing NaN.

_NaN_ is the only value in JS that is not equal to itself. NaN == NaN  ==> False


* *String*

Both _single quotes_ and _double quotes_ can be used to mark strings as long as the quotes at the start and the end of the string match.

_Newlines_ (Enter) can't be put between quotes, the string has to stay on a single line.

Strings can be compared in a way that strings are ordered is more or less alphabetc.

1. uppercase letters are always less than lowercase ones, for example, 'Z' < 'a'

2. non alphabetic characters are also included in the ordering.

3. The actual comparison is based on the *_Unicode_* starndard.

4. When comaring strings, JavaScript goes over them from left to right, comparing the numeric codes of the characters one by one.


* *Logical Operators*

JavaScript supports three logical operators, _and_, _or_ and _not_. The operators are repectively &&, || and !. _Or_ has the lower precedence, then comes &&, then the comparsion operators, then the rest.

* *Undefined Values*

There are two special values, written *null* and *undefined*, they are used to denote the absence of meaningful value. They are themselves values, but they carry no information.

* *Automatic Type Conversion*

When an operator is applied to the wrong type of value, JavaScrupt will quitely convert the value to the type it wants, using a set of tyles that often aren't what you want or expect, which is called type coercion.

When something that doesn't map to a number in an obvious way is converted to a number, the value _NaN_ is produced.

The rules of converting strings and numbers to Boolean values state that 0, NaN and the empty string("") count as false while all the other values count as true. Because of this, expression liek 0 == false and  "" == false are also true.

For precisee equal, use '===', it tests whether a value is precisely equal to the other. There is also '!==' which is not precisely equal.



### Program Structure

A fragment of code that produces code is called *expression*.

Variables can be defined by :

`var caught = 6`

Variable names can't include _spaces_, _digits_ can be part of variable names, but the name can't start with the digit, the name can't include punctuation except exclamation mark(!) and underscore(_)


When you define a variable without giving it a value, it points to nothing, the value fot the variable is _undefined_.


There are some words with special meaning, they are called _keyword_.

There are some words which are reserved for future use, they are called _reserved words_

### Functions

* *Defining a function*
A function definition is just a regular variable definition where the value given to to variabel happens to be a function. For example:
```javascript
var square = function(x){
	return x * x;
};

console.log(square(2));
// console shows 4
```

A function is created by a expression that starts with keyword _function_, functions could have a set of _parameters_ defined in the following paretheses, after parameter list, the body of the functions contains the statements that are executed when the function is called. The body of the function should always be wrapped in braces.

* *Parameters and Scopes*

A function can have multiple parameters or no paramtere at all. The parameters behave like variables, but its inital value is given by function caller.

An important property of functions is that the variables created inside of them including their parameters are lcoal to the function, which means, the variable and parameters in the function will be newly created every time the function is called and keep its own copy to avoid inteference.

The localness of variable applies only to the parameters and to variabls declared with the *_var_* keyword inside the function body, variables declared outside of any function are called global, since they are visible throughout the program. 

JS distinguishes not just between global and local variables, functions can be treated inside other functions, producing several degrees of locality.


In short, each local scope can also see the all the local scopes that contain it. The set of variable visible inside a function is determined by the place of that function in the program text.

All variables from blocks around a function's definition are visible, meaning both those in function bodies that enclose it and those at the top level of the porgram.

In js, braces doesn't produce a new local environment, but in JavaScript, * functions are the only things that create a new scope.*


* *Functions as Values*

Function variablles usually simply act as names for a specific piece of the progarm. Such a variable is defined once and never changed.

A *function value* can do all things that other values can do, it is possible to store a function value in a new place, pass it as an argument to a function.

A *variable* that holds a function is still just a regular variable and can be assigned a new value.


* *Declaratiion Notation*

The _function_ keyword can be used at the start of a statement, as in the following:
```javascript
function square(x) {
	return x * x;
}
```

This is a function declaration. The statement defines the variable _square_ and points it at the given function. 

Function declarations are not part of the regular top to bottom flow of control, they are conceptually moved to the *top of their scope* and can be used by all the code in that scope.